host: localhost
port: 8081
server:
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 30s
db:
  uri: postgresql://postgres:postgres@localhost:5432?connect_timeout=10
  connect_timeout: 30s
  request_timeout: 30s
executor:
  max_workers: 5
  max_concurrent_jobs: 100
