host: localhost
port: 8081
server:
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 30s
db:
  connect_timeout: 30s
  request_timeout: 30s
executor:
  max_workers: 5
  max_concurrent_jobs: 100
gitlab:
  host: gitlab.com
  group_parent_name: demo-grader-123
  user: DemoGrader
  user_email: demo.grader@abv.bg
