apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "grader.ui.configmap.name" . }}
data:
  env-config.js: |
    window._env_ = {
        GRADER_HOST: "localhost/api/v1",
        REACT_APP_GITLAB_HOST: "gitlab.com",
        REACT_APP_GROUP_PARENT_NAME: "demo-grader-123",
    }
