apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "grader.grader.ingress.name" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/limit-rps: "150"
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /api/v1/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "grader.grader.service.name" . }}
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ template "grader.ui.service.name" . }}
                port:
                  number: 80
