apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "grader.jobs.role.name" . }}
  namespace: {{ template "grader.jobs.namespace.name" . }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create"]
