apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "grader.jobs.rolebinding.name" . }}
  namespace: {{ template "grader.jobs.namespace.name" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "grader.jobexecutor.serviceaccount.name" . }}
  namespace: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "grader.jobs.role.name" . }}
