apiVersion: v1
kind: Service
metadata:
  name: {{ template "grader.grader.service.name" . }}
  labels:
    app: grader
spec:
  selector:
    app: grader
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
