apiVersion: v1
kind: Service
metadata:
  name: {{ template "grader.ui.service.name" . }}
  labels:
    app: grader-ui
spec:
  selector:
    app: grader-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
