apiVersion: v1
kind: Service
metadata:
  name: {{ template "grader.jobexecutor.service.name" . }}
  labels:
    app: grader-job-executor
spec:
  selector:
    app: grader-job-executor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
