apiVersion: v1
kind: Service
metadata:
  name: {{ template "grader.dockerexecutor.service.name" . }}
  labels:
    app: grader-docker-executor
spec:
  selector:
    app: grader-docker-executor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
