host: localhost
port: 8080
server:
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 30s
db:
  uri: postgresql://postgres:postgres@localhost:5432?connect_timeout=10
  connect_timeout: 30s
  request_timeout: 30s
job_executor:
  url: http://localhost:8081/job
github:
  client_id: xxx
  client_secret: xxx
  required_scope: user:email,repo
auth:
  access_token_secret: accesstokensecret
  access_token_expiration_time: 24h
  refresh_token_secret: refreshtokensecret
  refresh_token_expiration_time: 24h
