host: localhost
port: 8080
ingress_host: localhost:8080
ui_ingress_host: localhost:3000
server:
  read_timeout: 30s
  write_timeout: 30s
  shutdown_timeout: 30s
outbound:
  timeout: 30s
db:
  connect_timeout: 30s
  request_timeout: 30s
job_executor:
  host: http://localhost:8081
gitlab:
  host: gitlab.com
  admin_user_id: 10687808
  group_parent_id: 15645391
  group_parent_name: demo-grader-123
auth:
  access_token_expiration_time: 24h
  refresh_token_expiration_time: 24h
