apiVersion: v1
appVersion: "1"
name: grader
description: A Helm chart for grader service for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: 4.0.17
    repository: https://kubernetes.github.io/ingress-nginx
