postgresql:
  fullnameOverride: postgresql
  auth:
    postgresPassword: postgres
  volumePermissions:
    enabled: true
  persistence:
    size: 1Gi

ingress-nginx:
  controller:
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 2
      targetCPUUtilizationPercentage: 50
      targetMemoryUtilizationPercentage: 50
    resources:
      requests:
        memory: 300Mi
    scope:
      enabled: true
